name: Build Android
description: ""

inputs:
  package-id:
    description: 'Compiled Package ID'
    required: true
    default: 'release_Mobile'
  project-to-build:
    description: 'Relative path to .csproj file'
    required: true
    default: ''
  project-folder:
    description: 'csproj folder'
    required: true
    default: ''        
  artifact-retention-policy: 
    description: 'Number of days to keep the build artifacts'
    required: false
    default: '90'
  certificate: 
     description: "Base64 Certificate for signing .apk package"
     required: true    
  certificate-password: 
     description: "Certificate password"
     required: true      
  certificate-alias: 
     description: "Keystore alias"
     required: true        
runs:
  using: "composite"
  steps:
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'

    - name: GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
      with:
        useConfigFile: true
        configFilePath: ./.github/workflows/config/gitversion.yml

    # # Decode the base 64 encoded pfx and save the Signing_Certificate
    # - name: Decode the jks
    #   shell: pwsh
    #   run: |
    #     $jks_cert_byte = [System.Convert]::FromBase64String("${{ inputs.certificate }}")
    #     $certificatePath = "${{ inputs.package-id }}_TemporaryKey.jks"
    #     [IO.File]::WriteAllBytes("$certificatePath", $jks_cert_byte)

    - name: Decode the jks
      id: decode_keystore
      uses: timheuer/base64-to-file@v1
      with:
          fileName: "${{ inputs.package-id }}_TemporaryKey.jks"
          encodedString: ${{ inputs.certificate }}

    # Create the app package by building and packaging the project
    - name: Build and create package
      shell: pwsh
      run: |
        Get-ChildItem -Recurs
        Write-Host "Building ${{ inputs.package-id }}"

        dotnet publish  -c Release -p:TargetFramework=net6.0-android  -o .\bin\Release\ ${{ inputs.project-to-build }}
        /p:AndroidSigningKeyStore=${{ steps.decode_keystore.outputs.filePath }}
        /p:AndroidSigningStorePass=${{ inputs.certificate-password }}
        /p:AndroidSigningKeyAlias=${{ inputs.certificate-alias }} 

        Get-ChildItem -Recurs

        $finalPackageFolder = ".\artifacts"
        Write-Host "Creating package folder: $finalPackageFolder"
        New-Item -ItemType Directory -Force -Path $finalPackageFolder

        Get-ChildItem -Recurs

        $finalPackageName = "$finalPackageFolder\${{ inputs.package-id }}_${{ steps.gitversion.outputs.assemblySemVer }}.zip"
        Write-Host "Compressing final package: $finalPackageName"
        Compress-Archive -Path '.\bin\Release\*' -DestinationPath $finalPackageName

    # Remove the pfx
    - name: Remove the pfx
      shell: pwsh
      run: Remove-Item -path ${{ inputs.package-id }}_TemporaryKey.pfx

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "${{ inputs.package-id }}_${{ steps.gitversion.outputs.assemblySemVer }}" 
        path: |
          .\artifacts\**\*.aab
          .\artifacts\**\*.apk
        retention-days: ${{ inputs.artifact-retention-policy }}