-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgWNh2494llJwFGw/y
ZBtUCguJ9yW97xlYbLKdLAcGyDqgCgYIKoZIzj0DAQehRANCAARInvvnJDgDC/fS
FzO9L9RnBf/eUoS52/h/HaDO1CdmZgUGekIi8H6A0wiXd8NrBLytTJO24Qaksx8s
mItouZu3
-----END PRIVATE KEY-----