name: CI

on: 
  push:
    branches:
      - main
      - release/**

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release/**

env:
  SIGNING_CERTIFICATE: "MIIKOQIBAzCCCfUGCSqGSIb3DQEHAaCCCeYEggniMIIJ3jCCBg8GCSqGSIb3DQEHAaCCBgAEggX8MIIF+DCCBfQGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAjyoqiF2bCXOAICB9AEggTY5DPSvYTaf5a7/UX2FB1OdvoTpVmE2TejyRi/6YK0+988S8p0aZMkPwGwUgGUQAqRAYIth7zB1aLp2/98/E51MzQINglKFzV4We6n0X7su7pU7NV9Ib/+zscYUQpxTQ0cZz+rdHBvFSadlIwboXUeozNTzsbTFdVMMMZ1ZF2dQ1BsAEk1SgTv2MbKSwRbrNup6MmvmJm5AEtNEPkqa+HOS7wsxeFxroagQphX6gJk4Fje9AcUXULosIfvXeT3E0SPtNcyZ6M0YyiUG2IZonCC0IVMbriB364BLz+AOA+vI2MKgDSQM9UoZt5GRN6TNNTZYrrA5xcHihzP+/vRdSuFwu16RG5t34tUNw+J0QnJzwCZOVn30fERt6Q9ruxzUxQiLLII5oO4TitocxlAzBGWQSP1iRQOJkXWYLc4ouvxi3iYNeq5/9Nasxe0R9F0gRfP7H7nixfJ9f3uC5gE0uXzbTbtxtKb5+UGKKO+/5Or5T0sjC+UGlMts+L0fYJm8CVKMiSIrObSQXTmoFiu8Q9tDNEG3umv6PwqsDTQiUOBjUHLhIMVAtRnQSOhujZh2ajk9b7y60c9v0nxeqsKkTFtsWs7PRs9efHYa5nBMVIAhkAHA69rxLMMy1PU0hAzirSC3q5rHWweynUvSHaSf/XJQ50bV3De0hSOAyFZaR3VwSkWvA3D28kJgk3iEEcdBZ5O+vcDFMP9fVMpnaKJ0VF94dcFa7kUEC1KhZRLo7bY7aGAt4uNpstmdm75Ts5LSY4xZXyvSszbIeEeHKzOSz7ASGUJJMY0od77cezp3qbBE+C1isgGwry0BsACrHG8DrOTv2TuNufpENsuKsdErVkZLXxTwhC2A7LfKTX1R+AjuBFqXfYNW/2APA93aHKOvlvkY/xRjtnuMvipExYmq5jhqd8ypdclx32Tb/lGrn0eHW7R/0Tolh9Fai8ReXvBlY7oSlebrc1B94jN4dSp6b6osQCVx6aUBLvB0rzTdlDJcrvKIR7zH4GM2fx9Ppk8vJWrsE+uCghFpsqKwwWizXSXRAz8Ac52mvFU/4AgbKo8RaQtnIryz3HbsAoGmUEepcQVD+IERhF1AJwgaH52YVRLVoUnjQBwV0s/B0zDXFEcQfNOIaEU9xRDhXflJwZ5//K1rOdrnstI3akylqacS9f5lOmnwgTMF3nx1AvMH10hrUItrirVQYIXAG5c4JJGZO8IdSDpwJNi4ig9SjoowE2XBBkd1IcjuRuu0OgnugLzPv185RRoPi1NkgMHG36I2AA/kgdilDfR/cesmEsC69DZrRcwGki8LoPVPcshEj65E/YNDDRtQ15o1QX6bn6xJU7kxU2A1Qt+HMybM/TkgF7jf1+JjIWSaSREgVx5Gg0pPIRbEhiPNqcMqwZTxcSBAr+8hxFeppp1VFBcZqaVx+3ghcHsGlWksTHJZ7k5c2Azd1GLF7ydRQQ7rVIvbbJ7LhN6dtoDgKlIPRofAmspRG/lgTHm4gpyh1uFy+PRvOIGBSFbgEoQZiEO1jISUTp2T39tXzAz2kGxMQq+yCiRTrVQuOIIdgwwEirxeC7XWZP97lPkeBcMX4sTWulipP4YMgWvXY3+e2uyYeqMpS1hYHcO+p2lhVXmdUXVmD0RqgvTFsPQ5UVHGZNNtzGB4jANBgkrBgEEAYI3EQIxADATBgkqhkiG9w0BCRUxBgQEAQAAADBdBgkqhkiG9w0BCRQxUB5OAHQAZQAtADkAMgA2ADgAZQA2ADIAYgAtAGMANgA5AGUALQA0AGEAZQA1AC0AYgBmAGQAMQAtADcAOAAwADMANABkAGMAOAAwAGUAYwBkMF0GCSsGAQQBgjcRATFQHk4ATQBpAGMAcgBvAHMAbwBmAHQAIABTAG8AZgB0AHcAYQByAGUAIABLAGUAeQAgAFMAdABvAHIAYQBnAGUAIABQAHIAbwB2AGkAZABlAHIwggPHBgkqhkiG9w0BBwagggO4MIIDtAIBADCCA60GCSqGSIb3DQEHATAcBgoqhkiG9w0BDAEDMA4ECDFRnb4EOntVAgIH0ICCA4Dz4A/Ugc3FipxU9xFwlXAT9HLibvGw2RPUuCDZw4+8Y7LOWjvJNtSimfF1rLo5KMhysgV9KUo3EO3D8VsUj9SyQyai6Y5ErcBjdmQilt94O77rMWlNAQ3r2U6+mS46fHmVJTvmLdesuwSoDnouHfkq8A04c/gikrf694hzSv7JO4gao34dOJiT2uI4JTHCLg+BxKe/c8FLrWmfym5PPOGU5DEDsbspEre6GXdaCTl5Ew3WZQTGedNwxZhLZ8k4gyg8M4J96xnMLF0QUhfU1JnlQrYcWSWS9K3cThOGAaqzQ7qlkIhQArf0pjMBNyNfMLb8Iku7df9/FVVOKWjWNvc8MjcyaMnjTeoVUm1JBxxZY6T9swb7jzJ205sCB6k71YdXkktPM6Vs3pIAySBErK6xViAC5wjlB8ofGJmC0gXcI0GUx87IzzW/KAV8+1giMv4wAdnk7eF/jvbjtPsiqcdfiY3ILdSc2I+rhOJ+8CuaUNrt80JSDFTBLIZ/zhfeWbNR8nDyNIYDI8rhxtkjGIweASuwbd/2YX6YAJTJQu0/jlq7ewH38+G8WQYRmVpU3ixgHWqOPPGdJghzpqI9aHrrqxMXKaW5CbRmABmJLL1OUtth5UeSLTimonViHg82ff8Fs7JHHrCOnm97/oR7UpwTOPsb78IN/oMF1GAM+xnuwHr7h2CVOCwtSpn6AtNshQdbSp4OSRsu7M25FuAukn3H22mqFZr27A8/paPRsL9x7JT7vY4jygLTF2NodNOuVNvwx3thrMODAt3PUJNTqrK7URma1SN1Qmc0v1HEcEcyCPTNYlnlDUWWRCqpnunOZUqLaTeVTBhaTIJIUa3PoST2bcRlPmWpaA2Ts480JtHCHz8vMOIhwqDya44oYbefF2RFCsH29MlPdiGEcF/F5XVETMZH9pu+dnOVHlK7/UGQoK5nqcoLZMZm89q1UlaXDZh+rh7xOO4OrjT4a42eZZuaV8WhEuXfOJ/oAi7RXIecL/b2TdeLk4TApGRibz45wa2NuDfZxSPXk0S4KHmvYhYSW6XSe4ICMN0SYs/OsAOMM0OQVKzCnvmCqb211IaOYYnYsewVq0yXc7z0X8H2J+3i3ivEf3OSlg2z+ehrBYgnOw78s8FDHaXiZzD+vAyQRgLJ4p3aV8IGjpODgUr4S7VUaa816EiUrjAznYKNRetEHDA7MB8wBwYFKw4DAhoEFBfhQOdf23ZHaaPJDWLdqO5nyv3HBBTMTtMmS+KZiaQJdhFZNVUlkXY2gAICB9A="

jobs:
  build_tool:
    name: Build UNO
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
         fetch-depth: 0 

      - name: Install Dependencies
        uses: "./.github/workflows/steps/install_dependencies"         

      # - name: Build Windows
      #   uses: "./.github/workflows/steps/build_winUI"
      #   with:
      #     package-id: "Windows"
      #     certificate: "$SIGNING_CERTIFICATE"
      #     project-to-build: "Demo.Windows/Demo.Windows.csproj"  
      #     project-folder: "Demo.Windows" 

      # - name: Build WPF
      #   uses: "./.github/workflows/steps/build_desktop"
      #   with:
      #     package-id: "WPF"
      #     project-to-build: "Demo.Skia.WPF/Demo.Skia.WPF.csproj"  
                  
      # - name: Build GTK
      #   uses: "./.github/workflows/steps/build_desktop"
      #   with:
      #     package-id: "GTK"
      #     project-to-build: "Demo.Skia.Gtk/Demo.Skia.Gtk.csproj"       

      # - name: Build Linux
      #   uses: "./.github/workflows/steps/build_desktop"
      #   with:
      #     package-id: "Linux.FrameBuffer"
      #     project-to-build: "Demo.Skia.Linux.FrameBuffer/Demo.Skia.Linux.FrameBuffer.csproj"             
       
      - name: Build Mobile (Android)
        uses: "./.github/workflows/steps/build_mobile"
        with:
          package-id: "Mobile_Android"
          certificate:  "$SIGNING_CERTIFICATE"
          project-to-build: "Demo.Mobile/Demo.Mobile.csproj" 
          target-framework: "net6.0-android"
          project-folder: "Demo.Mobile" 

      # - name: Build Mobile (iOS)
      #   uses: "./.github/workflows/steps/build_mobile"
      #   with:
      #     package-id: "Mobile_iOS"
      #     project-to-build: "Demo.Mobile/Demo.Mobile.csproj" 
      #     target-framework: "net6.0-ios"

      # - name: Build Mobile (MacCatalyst)
      #   uses: "./.github/workflows/steps/build_mobile"
      #   with:
      #     package-id: "Mobile_MacCatalyst"
      #     project-to-build: "Demo.Mobile/Demo.Mobile.csproj" 
      #     target-framework: "net6.0-maccatalyst"

      # - name: Build Wasm
      #   uses: "./.github/workflows/steps/build_wasm"
      #   with:
      #     package-id: "Wasm"
      #     project-to-build: "Demo.Wasm/Demo.Wasm.csproj"   